---
- name: Converge
  hosts: all
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name:
          - dirmngr
          - gnupg
        state: present
        update_cache: yes
        # update only if the last update is older than one day
        cache_valid_time: 86400

  roles:
    - name: ome.omero_web
      src: https://github.com/pwalczysko/ansible-role-omero-web
      version: p312
    - name: ome.omero_web_django_prometheus
