---
- name: Converge
  hosts: all
  tasks:
    - name: install dirmngr
      apt:
        name:
          - dirmngr
          - gnupg
        state: present

  roles:
    - name: ome.omero_web
      src: https://github.com/pwalczysko/ansible-role-omero-web
      version: p312
    - name: ome.omero_web_django_prometheus
